# Servidor
server.port=8080

# Banco de Dados (Dinâmico)
# No Render, a variável costuma se chamar DATABASE_URL, mas você pode mapear como quiser
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/e_learning}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SMTP (Email)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${APP_EMAIL_USERNAME}
spring.mail.password=${APP_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Segurança e Admin 
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}

# Configurações de página
spring.data.web.pageable.default-page-size=10

spring.cache.type=redis